import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ profile, loaded }) {
  return (
    <div className="px-8">
      <Head>
        <title>MWIT SC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loaded ? (
        <div className="space-y-2">
          <div className="items-center text-center rounded-lg">
            <div className="ds-avatar">
              <div className="w-24 ds-mask ds-mask-squircle">
                <img src={profile.pictureUrl} />
              </div>
            </div>
            <h2 className=" text-base-content text-xl font-bold p-2">
              {profile.displayName}
            </h2>
          </div>
          <p>If a dog chews</p>
          <div className="ds-card-actions justify-end space-y-1">
            <button
              id="rigist"
              className="ds-btn ds-btn-primary ds-btn-block gap-1"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z"
                  clipRule="evenodd"
                />
              </svg>
              <span className="text-lg">ลงทะเบียนใช้งาน</span>
            </button>
            <button
              id="rigist"
              className="ds-btn ds-btn-secondary ds-btn-block gap-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M18 3a1 1 0 00-1.447-.894L8.763 6H5a3 3 0 000 6h.28l1.771 5.316A1 1 0 008 18h1a1 1 0 001-1v-4.382l6.553 3.276A1 1 0 0018 15V3z"
                  clipRule="evenodd"
                />
              </svg>
              <span className="text-lg">ส่งเรื่องถึงกน.</span>
            </button>
            <button
              id="rigist"
              className="ds-btn ds-btn-info ds-btn-sm ds-btn-outline ds-btn-block gap-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                  clipRule="evenodd"
                />
              </svg>
              <span className="text-md">ขั้นตอนการใช้งาน</span>
            </button>
            <button
              id="rigist"
              className="ds-btn ds-btn-error ds-btn-outline ds-btn-sm ds-btn-block gap-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                  clipRule="evenodd"
                />
              </svg>
              <span className="text-md">รายงานปัญหาการใช้งาน</span>
            </button>
            <div className="w-full justify-center items-center text-center text-2xs flex space-x-2">
              <span>MWIT SC Line Bot - V. 20220421.0</span>
            </div>
          </div>
        </div>
      ) : (
        <div className="items-center text-center pt-10 space-y-5">
          <div className="w-10 h-10 inline-block rounded-full bg-slate-400 animate-ping"></div>
          <span className="block text-lg">Loading</span>
        </div>
      )}
    </div>
  );
}
